#!/bin/bash
TS="-2 days"
QD=`date -d "-1 days" +%Y%m%d`
log_dir="/home/xdmod/log/"
[ ! -z "$1" ] && TS="$1"
echo "TS="$TS
/home/xdmod/bin/getpbsacct -u supermod -b "$(date -d "$TS" +%s)" -r chadmin1.ucar.edu -v  -p '/gpfs/pbs/server_priv/accounting/' --resources "{'cheyenne': '/^r*/'}" > ${log_dir}screenoutput${QD}getpbsacct.txt 2>${log_dir}error${QD}getpbsacct.txt
